#!/usr/bin/python
# -*- coding: utf-8 -*-

archivo = open("archivo.txt")
n = archivo.readline()
print n.rstrip('\n')
m = archivo.readline()
print m.rstrip('\n')
cn = []
gn = []
cambio = False
linea = archivo.readline()
while linea != '':
	numeros = linea.split(" ")
	if len(numeros) > 1:
		cambio = True
	nuevaLinea = []    
	for elem in numeros:
		nuevaLinea.append(elem.rstrip('\n'))
	if cambio:
		gn.append(nuevaLinea)
	else:
		cn.append(nuevaLinea)
	linea = archivo.readline()    
print cn
print gn 
archivo.close()

